CREATE TABLE IF NOT EXISTS  M_USER (
	 EMPLOYEENO INT IDENTITY
	,USERID VARCHAR(20) NOT NULL
	,USERNM VARCHAR(100) NOT NULL
	,PASSWORD VARCHAR(20) NOT NULL
	,DEPARTMENTCD VARCHAR(1) NOT NULL
	,POSITIONCD VARCHAR(1) NOT NULL
	,JOINED VARCHAR(6) NOT NULL
	,AGE INT NOT NULL
	,POSTALCD VARCHAR(7) NOT NULL
	,ADDRESS VARCHAR(200) NOT NULL
	,TELNO VARCHAR(13) NOT NULL
	,PRIMARY KEY (EMPLOYEENO)
);
CREATE TABLE IF NOT EXISTS  M_POSITION (
	 POSITIONCD VARCHAR(1) NOT NULL
	,POSITIONNM VARCHAR(30) NOT NULL
	,PRIMARY KEY (POSITIONCD)
);
CREATE TABLE IF NOT EXISTS  M_DEPARTMENT (
	 DEPARTMENTCD VARCHAR(1) NOT NULL
	,DEPARTMENTNM VARCHAR(30) NOT NULL
	,PRIMARY KEY (DEPARTMENTCD)
);
